package Proyecto;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fran
 */
public class Formacion extends javax.swing.JFrame {

    /**
     * Creates new form Formacion
     */
    public Formacion(){
        initComponents();
        
        String texto="";
        //cbTres.setLocation(250, 50);
        int i = 0;
        

        
        ComponentMover cm = new ComponentMover();
        cm.registerComponent(cbDos,cbSeis,cbTres,cbCuatro,cbCinco,cbCinco2,cbOcho,cbNueve,cbOnce,cbSiete);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Formacion1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        trescuatrotres = new javax.swing.JRadioButton();
        cuatrocuatrodos = new javax.swing.JRadioButton();
        cuatrotrestres = new javax.swing.JRadioButton();
        cbSiete = new javax.swing.JComboBox();
        cbNueve = new javax.swing.JComboBox();
        cbOcho = new javax.swing.JComboBox();
        cbCinco2 = new javax.swing.JComboBox();
        cbCinco = new javax.swing.JComboBox();
        cbOnce = new javax.swing.JComboBox();
        cbCuatro = new javax.swing.JComboBox();
        cbArquero = new javax.swing.JComboBox();
        cbSeis = new javax.swing.JComboBox();
        cbDos = new javax.swing.JComboBox();
        cbTres = new javax.swing.JComboBox();
        txtCanchita = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Guardar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, -1));

        jLabel1.setFont(new java.awt.Font("Aqua Grotesque", 0, 15)); // NOI18N
        jLabel1.setText("ELEGIR JUGADORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 19, 160, -1));

        Formacion1.add(trescuatrotres);
        trescuatrotres.setText("3-4-3");
        getContentPane().add(trescuatrotres, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, 30));

        Formacion1.add(cuatrocuatrodos);
        cuatrocuatrodos.setText("4-4-2");
        cuatrocuatrodos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cuatrocuatrodosStateChanged(evt);
            }
        });
        cuatrocuatrodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatrocuatrodosActionPerformed(evt);
            }
        });
        getContentPane().add(cuatrocuatrodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, 30));

        Formacion1.add(cuatrotrestres);
        cuatrotrestres.setText("4-3-3");
        getContentPane().add(cuatrotrestres, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, 30));

        cbSiete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        cbNueve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        cbOcho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        cbCinco2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbCinco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        cbCinco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        cbOnce.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbOnce, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        cbCuatro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        cbArquero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arquero" }));
        getContentPane().add(cbArquero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));

        cbSeis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        cbDos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        cbTres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tres" }));
        getContentPane().add(cbTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 70, -1));
        getContentPane().add(txtCanchita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 520, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 650, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuatrocuatrodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatrocuatrodosActionPerformed
       // String path = "/home/fran/Escritorio/4-4-2.png";  
       // URL url = this.getClass().getResource(path);  
       // ImageIcon icon = new ImageIcon(url);  
       // txtCanchita.setIcon(icon);  
        //txtCanchita.setIcon(new jImageIcon(getClass().getResource("/home/fran/Escritorio/4-4-2.png"))); 
    }//GEN-LAST:event_cuatrocuatrodosActionPerformed

    private void cuatrocuatrodosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cuatrocuatrodosStateChanged
       
    }//GEN-LAST:event_cuatrocuatrodosStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Formacion1;
    private javax.swing.JComboBox cbArquero;
    private javax.swing.JComboBox cbCinco;
    private javax.swing.JComboBox cbCinco2;
    private javax.swing.JComboBox cbCuatro;
    private javax.swing.JComboBox cbDos;
    private javax.swing.JComboBox cbNueve;
    private javax.swing.JComboBox cbOcho;
    private javax.swing.JComboBox cbOnce;
    private javax.swing.JComboBox cbSeis;
    private javax.swing.JComboBox cbSiete;
    private javax.swing.JComboBox cbTres;
    private javax.swing.JRadioButton cuatrocuatrodos;
    private javax.swing.JRadioButton cuatrotrestres;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton trescuatrotres;
    private javax.swing.JLabel txtCanchita;
    // End of variables declaration//GEN-END:variables
}
