package Proyecto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JFrame;


/**
 *
 * @author fran
 */

public class Nueva extends javax.swing.JFrame {




    /**
     * Creates new form Nueva
     */
    public Nueva() {
        initComponents();
        clean();
        load();
        
        
        
        
        this.setTitle("Team Manager");
        jsH1.setPaintLabels(true);
        jsH2.setPaintLabels(true);
        jsH3.setPaintLabels(true);
        jsH4.setPaintLabels(true);
        
        jsH2.setPaintTicks(true);
        jsH1.setPaintTicks(true);
        jsH3.setPaintTicks(true);
        jsH4.setPaintTicks(true);
        
        jsH1.setMajorTickSpacing(25);
        jsH2.setMajorTickSpacing(25);
        jsH3.setMajorTickSpacing(25);
        jsH4.setMajorTickSpacing(25);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        GrupoDeFormaciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jsH1 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        txtH1 = new javax.swing.JLabel();
        jsH2 = new javax.swing.JSlider();
        txtH2 = new javax.swing.JLabel();
        jsH3 = new javax.swing.JSlider();
        txtH3 = new javax.swing.JLabel();
        txtH4 = new javax.swing.JLabel();
        jsH4 = new javax.swing.JSlider();
        btPlantilla = new javax.swing.JButton();
        txtNombreEquipo = new javax.swing.JTextField();
        txtArquero = new javax.swing.JTextField();
        txtDefensa = new javax.swing.JTextField();
        txtMedio = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPajaro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListJugadores = new javax.swing.JList();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cabin", 0, 24)); // NOI18N
        jLabel1.setText("NUEVO EQUIPO");

        jsH1.setToolTipText("");
        jsH1.setValue(0);
        jsH1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH1StateChanged(evt);
            }
        });

        jLabel3.setText("Nombre del jugador");

        txtH1.setText("Arquero");

        jsH2.setValue(0);
        jsH2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH2StateChanged(evt);
            }
        });

        txtH2.setText("Defensa");

        jsH3.setValue(0);
        jsH3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH3StateChanged(evt);
            }
        });

        txtH3.setText("Medio");

        txtH4.setText("Ataque");

        jsH4.setValue(0);
        jsH4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH4StateChanged(evt);
            }
        });

        btPlantilla.setText("Mandar jugador a la plantilla");
        btPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlantillaActionPerformed(evt);
            }
        });

        txtNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEquipoActionPerformed(evt);
            }
        });

        txtArquero.setEditable(false);
        txtArquero.setText("0");
        txtArquero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArqueroActionPerformed(evt);
            }
        });

        txtDefensa.setEditable(false);
        txtDefensa.setText("0");
        txtDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDefensaActionPerformed(evt);
            }
        });

        txtMedio.setEditable(false);
        txtMedio.setText("0");
        txtMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedioActionPerformed(evt);
            }
        });

        txtAtaque.setEditable(false);
        txtAtaque.setText("0");
        txtAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtaqueActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre del equipo");

        jLabel10.setFont(new java.awt.Font("Cabin", 0, 24)); // NOI18N
        jLabel10.setText("JUGADOR");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jListJugadores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListJugadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtPajaro, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPlantilla))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(txtH1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jsH1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtArquero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jsH2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtH2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(48, 48, 48)))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtH3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jsH3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(344, 344, 344)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(278, 278, 278)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(211, 211, 211))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(328, 328, 328)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(260, 260, 260)
                                        .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtH4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jsH4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtH1)
                        .addGap(18, 18, 18)
                        .addComponent(jsH1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtH2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsH2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArquero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtH4)
                            .addComponent(txtH3))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsH4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsH3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPlantilla)
                    .addComponent(txtPajaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlantillaActionPerformed
        
        int H1 = jsH1.getValue();
        int H2 = jsH2.getValue();
        int H3 = jsH3.getValue();
        int H4 = jsH4.getValue();
        
        String nom = txtNombre.getText();
        
        String errores = "";
        
        txtNombreEquipo.getText();
        if(txtNombreEquipo==null){
            JOptionPane.showMessageDialog(new JFrame(), "Atencion debes colocar un nombre al equipo", "Upss", JOptionPane.ERROR_MESSAGE);
        }
        
        
        if (nom.length()==0){
            errores += "Debe ingresar un nombre\n";
            
            
        }
        if (errores.length()>0){
            return;
        }else{
            Jugador aux = new Jugador(nom, H1, H2, H3, H4);
 //           Equipo.jugador.add(aux);
            Cantera.addJugador(aux);
            
            
            
            
                    

          //  JugadorArrayList.add(0, "Elemento 1");
           // JugadorArrayList.get(0);
            
        }
        txtNombreEquipo.setEditable(false);   //Prevents editing
        txtNombreEquipo.setEnabled(false);
        
/*        int i = 0;
        Jugador[] jugadores = new Jugador[11];
        for (i=0; i<jugadores.length;i++){
            if (jugadores[i]==null){
                jugadores[i] = new Jugador(nom, H1, H2, H3, H4, choice);
                }
                }
        
        */

        clean();
    }//GEN-LAST:event_btPlantillaActionPerformed
       
    private void txtArqueroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArqueroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArqueroActionPerformed

    private void txtDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDefensaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDefensaActionPerformed

    private void txtMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedioActionPerformed

    private void txtAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtaqueActionPerformed

    private void jsH1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH1StateChanged
        // TODO add your handling code here:
                txtArquero.setText(String.valueOf(jsH1.getValue()));        
    }//GEN-LAST:event_jsH1StateChanged

    private void jsH2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH2StateChanged
        // TODO add your handling code here:
                txtDefensa.setText(String.valueOf(jsH2.getValue()));          
    }//GEN-LAST:event_jsH2StateChanged

    private void jsH3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH3StateChanged
                txtMedio.setText(String.valueOf(jsH3.getValue()));  
    }//GEN-LAST:event_jsH3StateChanged

    private void jsH4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH4StateChanged
                txtAtaque.setText(String.valueOf(jsH4.getValue()));  
    }//GEN-LAST:event_jsH4StateChanged

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed


// TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEquipoActionPerformed

    }//GEN-LAST:event_txtNombreEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() { 
           public void run() {                
               new Nueva().setVisible(true);
          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoDeFormaciones;
    private javax.swing.JButton btPlantilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JList jListJugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jsH1;
    private javax.swing.JSlider jsH2;
    private javax.swing.JSlider jsH3;
    private javax.swing.JSlider jsH4;
    private javax.swing.JTextField txtArquero;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextField txtDefensa;
    private javax.swing.JLabel txtH1;
    private javax.swing.JLabel txtH2;
    private javax.swing.JLabel txtH3;
    private javax.swing.JLabel txtH4;
    private javax.swing.JTextField txtMedio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JLabel txtPajaro;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Equipo> arrayEqui = new ArrayList();
    private void clean() {
        Cantera.load();
        this.txtArquero.setText("0");
        this.txtDefensa.setText("0");
        this.txtAtaque.setText("0");

        this.txtMedio.setText("0");
        this.txtNombre.setText("");
        this.jsH1.setValue(0);
        this.jsH2.setValue(0);
        this.jsH3.setValue(0);
        this.jsH4.setValue(0);
        
        
        
        
        
        
        load();

    }

            
    private void load() {
        
        if (Cantera.getCantidadDeJugadores()>11){
            JOptionPane.showMessageDialog(new JFrame(), "Atencion ya pusiste los 11 jugadores", "Plantilla Completa", JOptionPane.ERROR_MESSAGE);
            Formacion formacion= new Formacion();
            formacion.setVisible(true);
            this.setVisible(false);
            formacion.setLocationRelativeTo(null);
            String nomb = txtNombreEquipo.getText();
            
        }else{
                DefaultListModel model = new DefaultListModel();
        for (Jugador jugador : Cantera.getJugadores()) {
            model.addElement(jugador);

            
        }
        Equipo e = new Equipo(txtNombreEquipo.getText(),Cantera.getJugadores());
        e.getEquipo();
        

        arrayEqui.add(e);
            System.out.println(arrayEqui.get(0).nombreEquipo);
            System.out.println(arrayEqui.get(0).nombreArrayList);
        System.out.println(e.getEquipo().toString());
        jListJugadores.setModel(model);
        
        } 
    }
}



    

